[build]
  publish = "src"   # Set this to "src" to publish files from the `src` folder

[functions]
  directory = "netlify/functions"  # Correct if using serverless functions (no changes needed here)

[build.environment]
  NODE_ENV = "production"